version: '3.1'

services:
  stats-db:
    image: postgres:15.1-alpine
    container_name: EWM-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - stats-db-data:/var/lib/postgresql/data

  stats-server:
    restart: on-failure
    build: ./stats-service/stats-server
    image: stats-server-image
    container_name: ewm-stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - DB_NAME=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=stats-db
      - DB_PORT=5432
      - SPRING_PROFILES_ACTIVE=docker

  ewm-db:
    image: postgres:15.1-alpine
    container_name: EWM-server-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ewm-db-data:/var/lib/postgresql/data

  ewm-service:
    build: ./main-service
    image: ewm-service-image
    container_name: ewm-service
    depends_on:
      - ewm-db
      - stats-server
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=ewm-server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - STATS_SERVER_URL=http://ewm-stats-server:9090
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  stats-db-data:
  ewm-db-data: